use_frameworks!

platform :ios, '11.0'
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = "A9LKE94T63"
         end
    end
  end
end

target 'EasyDebug_Example' do
  pod 'EasyDebug', :path => '../'
  pod 'SwiftLint', :configurations => ['Debug']
  pod 'Alamofire'
  pod 'CocoaLumberjack/Swift'
  
  pod 'LookinServer', :configurations => ['Debug']
  target 'EasyDebug_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
